// <auto-generated />
namespace TheatreSystem.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class dbInit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbInit));
        
        string IMigrationMetadata.Id
        {
            get { return "201601161636286_dbInit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
